# Generated by Django 2.2.7 on 2019-11-29 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='correo electronico')),
                ('tipoUsuario', models.CharField(choices=[('AS', 'Astronomo'), ('AF', 'Aficionado')], default='AF', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Observatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('camara', models.CharField(max_length=50)),
                ('apertura', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('filtros', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desarrollo.Usuario')),
            ],
        ),
    ]
