# Generated by Django 2.2.6 on 2020-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatorio',
            name='opcionInscripcion',
            field=models.CharField(choices=[('POS', 'Positivo'), ('NEU', 'Neutro'), ('NEGA', 'Negativo')], default='NEU', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='inscripciones',
            unique_together={('observaciones', 'observatorios')},
        ),
    ]
