# Generated by Django 2.2.6 on 2020-02-20 00:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('camara', models.CharField(max_length=50)),
                ('apertura', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('filtros', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('distanciaFocal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(limit_choices_to={'tipoUsuario': 'AF'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_observacion', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=100)),
                ('duracion_ocultacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_final', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='observacion/')),
                ('user', models.ForeignKey(limit_choices_to={'tipoUsuario': 'AT'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inscripciones/')),
                ('opcionInscripcion', models.CharField(choices=[('POS', 'Positivo'), ('NEU', 'Neutro'), ('NEGA', 'Negativo')], default='NEU', max_length=9)),
                ('observaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Observacion')),
                ('observatorios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Observatorio')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
