# Generated by Django 2.2.6 on 2020-02-23 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_remove_notificaciones_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
