# Generated by Django 2.2.6 on 2020-02-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_remove_inscripciones_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inscripciones/'),
        ),
    ]
