# Generated by Django 2.2.6 on 2020-01-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_auto_20200125_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(choices=[('AT', 'Atro'), ('AF', 'Aficionado')], default='AF', max_length=9),
        ),
    ]
