# Generated by Django 2.2.6 on 2020-02-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_inscripciones_observacion_observatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='image',
        ),
        migrations.RemoveField(
            model_name='inscripciones',
            name='opcionInscripcion',
        ),
    ]
