# Generated by Django 2.2.6 on 2020-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_auto_20200321_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='observatorio',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='observatorio',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
