# Generated by Django 2.2.6 on 2020-01-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0003_usuario_tipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_astronomo',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='user',
            field=models.ForeignKey(limit_choices_to={'tipoUsuario': 'AT'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observatorio',
            name='user',
            field=models.ForeignKey(limit_choices_to={'tipoUsuario': 'AF'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_Aficionado',
        ),
        migrations.DeleteModel(
            name='User_Astronomo',
        ),
    ]
