# Generated by Django 2.2.6 on 2020-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0003_notificaciones_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipoNotificacion',
            field=models.CharField(choices=[('SOLICITUD', 'Solitita cambio a Usuario Astro'), ('OBSERVACION_MODIFICADA', 'ha habido Modificacion en la observacion'), ('NONE', 'Ninguna')], default='NONE', max_length=150),
        ),
    ]
