# Generated by Django 2.2.6 on 2020-01-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_auto_20200129_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
