# Generated by Django 2.2.6 on 2020-03-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_auto_20200223_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='tipoNotificacion',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='id_notificacion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Observacion'),
        ),
        migrations.AlterField(
            model_name='observatorio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
