# Generated by Django 2.2.6 on 2020-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_auto_20200302_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
