# Generated by Django 2.2.6 on 2020-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_remove_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacion',
            options={'verbose_name_plural': 'Observaciones'},
        ),
        migrations.DeleteModel(
            name='Inscripciones',
        ),
    ]
