# Generated by Django 2.2.6 on 2020-01-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0006_auto_20200130_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('Observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Observacion')),
                ('observatorios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Observatorio')),
            ],
        ),
    ]
