# Generated by Django 2.2.6 on 2020-03-04 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0007_auto_20200302_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
