# Generated by Django 2.2.6 on 2020-01-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0007_inscripciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='Observacion',
            new_name='observaciones',
        ),
        migrations.AlterIndexTogether(
            name='inscripciones',
            index_together={('observaciones', 'observatorios')},
        ),
    ]
