# Generated by Django 2.2.6 on 2020-01-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0008_auto_20200130_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('inscripciones_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desarrollo.Inscripciones')),
            ],
            bases=('desarrollo.inscripciones',),
        ),
        migrations.AlterIndexTogether(
            name='inscripciones',
            index_together=set(),
        ),
    ]
