# Generated by Django 2.2.6 on 2020-01-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0009_auto_20200130_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripciones',
            unique_together={('observaciones', 'observatorios')},
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
