# Generated by Django 2.2.6 on 2020-02-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0010_auto_20200130_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripciones',
            options={'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='inscripciones',
            unique_together=set(),
        ),
    ]
