# Generated by Django 2.2.6 on 2020-02-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0011_auto_20200204_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacion',
            options={'verbose_name_plural': 'Observaciones'},
        ),
    ]
