# Generated by Django 2.2.6 on 2020-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0012_auto_20200204_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/%s'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observacion/%Y/%m/%D/'),
        ),
    ]
