# Generated by Django 2.2.6 on 2020-02-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0014_auto_20200210_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='usuarios/'),
        ),
    ]
