# Generated by Django 2.2.6 on 2020-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0017_auto_20200210_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='usuarios/default_image.png', upload_to='usuarios/'),
        ),
    ]
