# Generated by Django 2.2.6 on 2020-02-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0018_auto_20200210_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='usuarios/'),
        ),
    ]
