# Generated by Django 2.2.6 on 2020-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0020_auto_20200211_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='solicitudAstro',
            field=models.BooleanField(default=False, verbose_name='Solicitud Usuario Astrofisico '),
        ),
    ]
