# Generated by Django 2.2.6 on 2020-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0021_auto_20200211_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observacion/'),
        ),
    ]
