# Generated by Django 2.2.6 on 2020-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0022_auto_20200212_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observacion/%Y/%m/%D/'),
        ),
    ]
