# Generated by Django 2.2.6 on 2020-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0024_auto_20200214_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='id',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='id_inscripcion',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
