# Generated by Django 2.2.6 on 2020-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0025_auto_20200217_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripciones',
            name='id_inscripcion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
