# Generated by Django 2.2.6 on 2020-02-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0026_auto_20200217_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='id_inscripcion',
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
