# Generated by Django 2.2.6 on 2020-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0028_auto_20200217_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='image',
            field=models.ImageField(default=0, upload_to='inscripciones/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='opcionInscripcion',
            field=models.CharField(choices=[('POS', 'Positivo'), ('NEU', 'Neutro'), ('NEGA', 'Negativo')], default='NEU', max_length=9),
        ),
    ]
